### ISSUE TITLE
Awesome, but how do you use it? 

### ISSUE THREAD

**Issue by birchcode** [chrissicool/zsh-256color#3]
Any chance you could post an example theme using additional colors?

Tried replacing some of the standard colors (blue, cyan etc) with some of the xterm 256 colors listed  at https://jonasjacek.github.io/colors/ but no luck

**Comment by chrissicool** [comment]
This plugin only enables 256 color mode on terminals that support it. If you have this plugin enabled, you can check if your terminal is capable of 256 colors by checking the `$TERM` environment variable. If it ends in '-256color', then everything is fine. Otherwise your terminal does not support 256 colors.

There are a bunch of themes available in [OhMyZsh](https://github.com/robbyrussell/oh-my-zsh) that leverage 256 colors. E.g. 'half-life' supports both, 16 colors and 256 colors. Whereas the 'sporty_256' theme only supports 256 colors.

The way that the color palette is displayed depends on your terminal emulator program. E.g. GnomeTerminal lets you edit the palette, for the base 16 colors at least. Others may have similar options. But in general, the color palette is fix.

Hope this helps.

**Comment by birchcode** [comment]
That helps a lot! Yeah my term is 256 and the plugin enabled but had no idea how to call the colours. 

After looking in the half-life theme as you suggested, I saw how they did it, e.g.

Defining it by:
```
    turquoise="%F{81}"
    orange="%F{166}"
    purple="%F{135}"
    hotpink="%F{161}"
    limegreen="%F{118}"
```

Then using it by:
```
{$turquoise}something
```

Thanks
